// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfDpKxTXWpPJ6rdiC2Vv2e0GwpqxbYZI',
    appId: '1:731899093719:web:f716268566b0e31e308692',
    messagingSenderId: '731899093719',
    projectId: 'smarthome-be050',
    authDomain: 'smarthome-be050.firebaseapp.com',
    storageBucket: 'smarthome-be050.appspot.com',
    measurementId: 'G-QG7PKRYNL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnXJaBCktX89X076oRt6h_IDiYUtX9wC4',
    appId: '1:731899093719:android:07cc60c67a2d158a308692',
    messagingSenderId: '731899093719',
    projectId: 'smarthome-be050',
    storageBucket: 'smarthome-be050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWD_dhFogSPhYEt5tgiF5QPJQOIaejhvk',
    appId: '1:731899093719:ios:137329d93b8f481f308692',
    messagingSenderId: '731899093719',
    projectId: 'smarthome-be050',
    storageBucket: 'smarthome-be050.appspot.com',
    iosClientId: '731899093719-vnnhp273ldb89jvuum5fgv7bvc1au46q.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWD_dhFogSPhYEt5tgiF5QPJQOIaejhvk',
    appId: '1:731899093719:ios:137329d93b8f481f308692',
    messagingSenderId: '731899093719',
    projectId: 'smarthome-be050',
    storageBucket: 'smarthome-be050.appspot.com',
    iosClientId: '731899093719-vnnhp273ldb89jvuum5fgv7bvc1au46q.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiIot',
  );
}
